// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace N8N.API.Context.Entities;

public partial class NotificationTemplate
{
    public Guid TemplateId { get; set; }

    public string Name { get; set; }

    public string SubjectName { get; set; }

    public string BodyTemplate { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public DateTimeOffset ModifiedAt { get; set; }

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();
}