// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace N8N.API.Context.Entities;

public partial class Notification
{
    public Guid NotificationId { get; set; }

    public Guid? EventId { get; set; }

    public Guid? UserId { get; set; }

    public Guid? TemplateId { get; set; }

    public string EventType { get; set; }

    public DateTimeOffset ScheduledTime { get; set; }

    public DateTimeOffset? SentAt { get; set; }

    public string Status { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public DateTimeOffset ModifiedAt { get; set; }

    public virtual Event Event { get; set; }

    public virtual NotificationTemplate Template { get; set; }

    public virtual User User { get; set; }
}