// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace N8N.API.Context.Entities;

public partial class Subscription
{
    public Guid SubscriptionId { get; set; }

    public Guid? UserId { get; set; }

    public Guid? EventId { get; set; }

    public DateTime SubscribedAt { get; set; }

    public bool IsActive { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public DateTimeOffset ModifiedAt { get; set; }

    public virtual Event Event { get; set; }

    public virtual User User { get; set; }
}